name: flutter_scaffold
description: A new Flutter application.

version: 1.0.4+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  carousel_slider: ^1.3.1
  transparent_image: ^1.0.0
  cached_network_image: ^2.0.0
  # cached_network_image: ^1.1.1
  smooth_star_rating: ^1.0.3
  http: ^0.12.0+2
  provider: ^3.1.0+1
  flutter_secure_storage: ^3.3.1+1
  fluttertoast: ^3.1.3
  flutter_staggered_grid_view: ^0.3.0
  firebase_database: ^3.1.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.12.9+5
  url_launcher: ^5.4.1
  google_sign_in: ^4.1.1
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.6+1
  webview_flutter: ^0.3.19+9
  flappy_search_bar: 1.4.1
  cupertino_icons: ^0.1.2
  share: ^0.6.3+6
  firebase_dynamic_links: ^0.5.0+11
  firebase_messaging: ^6.0.12
  carousel_pro: ^1.0.0
  cache_image: ^1.0.5
  flutter_advanced_networkimage: any
  lazy_load_scrollview: 1.0.1
  in_app_update: ^1.1.7
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/bruhh.PNG"
  adaptive_icon_background: "#191919"
  adaptive_icon_fore ground: "dev_assets/bruhh.PNG"

flutter:
  uses-material-design: true
  assets:
    - assets/images/loading.gif
    - assets/images/new.jpg
    - assets/images/men.jpg
    - assets/images/women.jpg
    - assets/images/gadgets.jpg
    - assets/images/gifts.jpg
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancing_script.ttf
